version: "3.4"

services:
  mysql:
    image: mysql:8.0.33-oracle
    container_name: nextshop_mysql
    restart: no
    volumes:
      - nextshop_db:/var/lib/mysql
      - ./dumps:/var/dumps
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nextshop_mysql
    ports:
      - 3306:3306
    networks:
      - nextshop
networks:
  nextshop:
volumes:
  nextshop_db: {}
